AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Lambda Gin
Resources:
  PokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: "cmd/lambda"
      Runtime: go1.x
      Role: "arn:aws:iam::565555147445:role/core-data-common-CoreDataLambdaRole-dev"
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 3
      Events:
        GetPokemonByName:
          Type: Api
          Properties:
            Path: /pokemon/{name}
            Method: GET
        GetOGPokemonList:
          Type: Api
          Properties:
            Path: /og
            Method: GET
Outputs:
  PokemonGinApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/hadza'
    Export:
      Name: SampleGinApi
